### ISSUE TITLE
Fix typos and naming

### ISSUE THREAD

**Issue by 0x7171** [flashfish0x/yearn-affiliate-tracker#1]
* [x] affilaiteId -> affiliateId: https://github.com/flashfish0x/yearn-affiliate-tracker/blob/98bc6ed5dab19c6380c83d548237dd8431dca0b7/contracts/YearnAffiliateTracker.sol#L35 and more occurrences all across the codebase
* [x] refferredBalance -> referredBalance https://github.com/flashfish0x/yearn-affiliate-tracker/blob/98bc6ed5dab19c6380c83d548237dd8431dca0b7/contracts/YearnAffiliateTracker.sol#L57
* [ ] Generally good to pass entire codebase through a spell checker 
* [x] Jiji comment: I would find & replace `affiliate` with `partner` across the entire code base (and repo name) to make it consistent with our naming elsewhere 
* [ ] RareWeasel feedback: I would change function name to requireIsVaultEndorsed or requireIsRegistered: https://github.com/flashfish0x/yearn-affiliate-tracker/blob/main/contracts/YearnAffiliateTracker.sol#L62

**Comment by flashfish0x** [comment]
Done https://github.com/flashfish0x/yearn-affiliate-tracker/commit/c91ac9c96e01459b1f6a4b59538e555e6edd623b

**Comment by flashfish0x** [comment]
Also changed all affiliate to  partner

**Comment by 0x7171** [comment]
looks good enough to me, closing
