### ISSUE TITLE
Save one transfer in deposit()

### ISSUE THREAD

**Issue by 0x7171** [flashfish0x/yearn-affiliate-tracker#3]
> https://github.com/flashfish0x/yearn-affiliate-tracker/blob/main/contracts/YearnAffiliateTracker.sol#L51
> Here you should use `deposit(amount, msg.sender)` you will save one one transfer
> 
> https://github.com/yearn/yearn-vaults/blob/main/contracts/Vault.vy#L864

**Comment by flashfish0x** [comment]
done https://github.com/flashfish0x/yearn-affiliate-tracker/commit/c91ac9c96e01459b1f6a4b59538e555e6edd623b

**Comment by 0x7171** [comment]
@pandadefi - have a look and close if looks good?

**Comment by pandadefi** [comment]
Good
