### ISSUE TITLE
Double counting issue

### ISSUE THREAD

**Issue by 0x7171** [flashfish0x/yearn-affiliate-tracker#5]
Based on the description in the README, it's possible for multiple partners to get attributed the same TVL ie double counting: 

1. User deposits 10k DAI using `referralCodeA` and gets 9k yvDAI sent to `walletX`
2. User withdraws 9k yvDAI for 10k DAI
3. User deposits 10k DAI again, this time using `referralCodeB` and gets 9k yvDAI sent to `walletX`.
4. User now has 9k yvDAI in their wallet and affiliates A and B have 9k in their affiliate balance.

According to the README calc, both A and B would get affiliate credit for this.

**Comment by flashfish0x** [comment]
I agree. Have updated readme to show last in priority
