### ISSUE TITLE
Transfer tokens after modifiying the state variables

### ISSUE THREAD

**Issue by 0x7171** [flashfish0x/yearn-affiliate-tracker#7]
@rareweasel:

>     - I always prefer to transfer the tokens after modifing the state variables: https://github.com/flashfish0x/yearn-affiliate-tracker/blob/main/contracts/YearnAffiliateTracker.sol#L54

**Comment by flashfish0x** [comment]
No longer relevant after the changes as per issue 3 https://github.com/flashfish0x/yearn-affiliate-tracker/issues/3

**Comment by 0x7171** [comment]
@rareweasel FYI quote above - closing
